.github/workflows/package-tests.yaml, packages/clang-format/package.yaml, packages/clarinet/package.yaml, packages/clojure-lsp/package.yaml, packages/cmakelang/package.yaml, packages/codelldb/package.yaml, packages/codespell/package.yaml, packages/commitlint/package.yaml, packages/cpplint/package.yaml, packages/crystalline/package.yaml, schemas/enums/language.json, schemas/enums/platform.json
Adds
- clang-format
- clarinet
- clojure-lsp
- cmakelang
- codelldb
- codespell
- commitlint
- cpplint
- crystalline
=> feat: add more packages

packages/reason-language-server/package.yaml, packages/remark-cli/package.yaml, packages/remark-language-server/package.yaml, packages/reorder-python-imports/package.yaml, packages/rescript-lsp/package.yaml, packages/revive/package.yaml, packages/robotframework-lsp/package.yaml, packages/rome/package.yaml, packages/rstcheck/package.yaml
Adds:
- reason-language-server
- remark-cli
- remark-language-server
- reorder-python-imports
- rescript-lsp
- revive
- robotframework-lsp
- rome
- rstcheck
=> feat: more packages

renovate.json5
Reverts mason-org/mason-registry#159
=> Revert "chore(renovate): update commitMessage"

packages/stylelint/package.yaml, schemas/enums/language.json
Apologies in advance – first time doing this! Hopefully this is in the correct format.
Closes https://github.com/williamboman/mason.nvim/issues/695.
=> feat: add stylelint

packages/pylyzer/package.yaml
This change introduces adding `pylyzer` which is a blazingly fast Python LSP written in Rust.
=> feat: add pylyzer

packages/millet/package.yaml, schemas/enums/language.json
Closes williamboman/mason.nvim#1097.
=> feat: add millet lsp

packages/htmlbeautifier/package.yaml
Add the [htmlbeautifier](https://github.com/threedaymonk/htmlbeautifier) to Mason registry.
First PR for Mason, so please let me know if something is missing/incorrect. Thanks!
=> Add htmlbeautifier

packages/dot-language-server/package.yaml
Closes https://github.com/williamboman/mason.nvim/issues/1237.
=> fix(dot-language-server): add bin entry

packages/standardjs/package.yaml
Closes https://github.com/williamboman/mason.nvim/issues/1279.
=> feat: add standardjs

packages/purescript-tidy/package.yaml
=> Add purescript-tidy

packages/pyink/package.yaml
Pying is a black fork that add a lot of useful features like doc format, allow define the number of identity spaces.
=> feat: add pyink python code formatter

packages/lean-language-server/package.yaml, schemas/enums/language.json
Closes https://github.com/williamboman/mason.nvim/issues/1317
=> feat: add lean-language-server

packages/nim-langserver/package.yaml, packages/nimlangserver/package.yaml
Adds support for [`nim-langserver`](https://github.com/nim-lang/langserver).
=> add nimlangserver

packages/vale-ls/package.yaml, packages/vale/package.yaml
Closes https://github.com/williamboman/mason.nvim/issues/1383.
=> feat: add vale-ls

packages/markuplint/package.yaml
This closes https://github.com/williamboman/mason.nvim/issues/1387.
=> feat: add markuplint

packages/verible/package.yaml
change verible version to 
v0.0-3318-g8d254167 
from
v0.0-3187-gb5a2cf2d
=> bump(verible): update to v0.0-3318-g8d254167

packages/rustfmt/package.yaml, packages/xo/package.yaml
I should probably proofread these in the future.
=> chore: improve deprecation copy

packages/sonarlint-language-server/package.yaml
Still not semver-compliant 😮 I'm not sure but does the Mend Renovate bot not offer some configuration regarding automatically detecting changes just for one artifact? I'm totally fine with updating myself manually every time, but automation is key nevertheless 😄
=> bump(sonarlint-language-server): update to v3.20.2

packages/asmfmt/package.yaml
Add asmfmt, formatter for assembly. Install with go.
=> feat: add asmfmt

packages/elixir-next-ls/package.yaml, packages/nextls/package.yaml
Hi!
First time making one of these. Please let me know of any adjustments needed. I have not been able to test it yet since I am not sure how. Will be working through that while this PR is open.
=> feat: add nextls

packages/snyk-ls/package.yaml, schemas/enums/language.json
Adds the Snyk language server
I have not been able to test this locally and would appreciate some help in how to do so
=> feat: add snyk-ls

packages/cmakelang/package.yaml
=> feat(cmakelang): add YAML support

packages/apex-language-server/package.yaml
=> feat(apex-language-server): link apex-jorje-lsp.jar

packages/markdownlint-cli2/package.yaml
Closes <https://github.com/williamboman/mason.nvim/issues/1507>
=> feat: add markdownlint-cli2

packages/sqlfmt/package.yaml
Support `jinja` tags, see http://sqlfmt.com/
=> feat(sqlfmt): add extra `jinjafmt`

packages/gci/package.yaml
https://github.com/daixiang0/gci
https://pkg.go.dev/github.com/daixiang0/gci
=> feat: add gci

packages/netcoredbg/package.yaml
=> bump(netcoredbg): update to 3.0.0-1012

packages/woke/package.yaml
First time I am adding a registry that is not simple copypaste from a similar registry. Kudos for the detailed guidelines, made it much easier.
The release page for reference: https://github.com/get-woke/woke/releases
=> feat: add woke

packages/tlint/package.yaml
adds tlint
skip test for win_x64 - see #3236
=> feat: add tlint

packages/zprint-clj/package.yaml
add zprint-clj (js wrapper) for #3239
might help windows users
=> feat: add zprint-clj

packages/detekt/package.yaml
A linter for kotlin!
closes https://github.com/williamboman/mason.nvim/issues/1554
=> feat: add detekt

packages/custom-elements-languageserver/package.yaml
Heya, Author of Custom Elements Language Server here. Updating the filetypes of the plugin to support all files. Also cleaning up some of the docs around installation
=> docs(custom-elements-ls): Update docs, version and languagelist

packages/hydra-lsp/package.yaml
Adding LSP for YAML configuration files based on Hydra python package for scientific projects https://hydra.cc/ 
https://github.com/Retsediv/hydra-lsp
=> feat: add hydra-lsp

packages/autotools-language-server/package.yaml
Here the respective PR at nvim-lspconfig: https://github.com/neovim/nvim-lspconfig/pull/2902
=> feat: add autotools-language-server

packages/jsonnetfmt/package.yaml
I'd love to have this in mason.
=> feat: Add jsonnetfmt

packages/oelint-adv/package.yaml
Linter for [bitbake](https://en.wikipedia.org/wiki/BitBake) recipes.
=> feat: add oelint-adv

packages/pkgbuild-language-server/package.yaml
The package seems to have completely disappeared from the internet.
=> chore(pkgbuild-language-server): add deprecation

packages/oelint-adv/package.yaml, schemas/enums/language.json
Update languages following discussion on #3724.
=> chore(oelint-adv): update languages

packages/sonarlint-language-server/package.yaml
(Copied from the last PR because it is still the same)
Once again, not semver-compliant 😞 At last after Christmas I'll find the time to create an automation on our side to find the newest version and create a PR ^^
=> bump(sonarlint-language-server): update to v4.2.2

packages/lightning-language-server/package.yaml, packages/lwc-language-server/package.yaml
Created this based on the contribution guidelines and after reading many example's in this repo, this is my first open source contribution (also my first time doing anything with an LSP, and am new to nvim) so a look over with a magnifier and some patience would be much appreciated! 
I'm unsure how to go about testing this, however there was a line on the contribution guidelines that led me to believe
it would be much easier to do so once a PR was made.
"Testing a package locally is still a bit complicated, open a PR early to make use of the cross-platform CI suite!"
=> feat: add LWC language server

packages/checkmake/package.yaml, schemas/enums/language.json
checkmake is a linter for makefiles written in go
=> feat: add checkmake

packages/pyproject-flake8/package.yaml
=> fix: naming pyproject-flake8 package

packages/sonarlint-language-server/package.yaml
Not semver-compliant 😞 But I'll stick with doing it manually.
=> bump(sonarlint-language-server): update to v4.3.0

packages/vscode-solidity-server/package.yaml, packages/vscode-solidity/package.yaml
as per https://github.com/neovim/nvim-lspconfig/pull/3011
=> feat: vscode-solidity

packages/glsl_analyzer/package.yaml, schemas/enums/language.json
This resolves https://github.com/williamboman/mason.nvim/issues/625
=> feat: add glsl_analyzer

packages/crystalline/package.yaml
Added Support for Crystalline on MacOS Arm.
=> Added Support for Crystalline on MacOS Arm.

packages/twig-cs-fixer/package.yaml
add [twig-cs-fixer](https://github.com/VincentLanglet/Twig-CS-Fixer)
=> feat: add twig-cs-fixer

packages/zeek-language-server/package.yaml, schemas/enums/language.json
I added the zeek-language-server, I have no clue how to test it so I dont know if I did it correctly
=> added zeek-language-server

packages/ocaml-lsp/package.yaml
https://github.com/ocaml/ocaml-lsp/releases/tag/1.17.0
=> bump(ocaml-lsp): update to 1.17.0

packages/ocamlformat/package.yaml
https://github.com/ocaml-ppx/ocamlformat/releases/tag/0.26.1
=> bump(ocamlformat): update to 0.26.1

packages/cortex-debug/package.yaml
https://github.com/mason-org/mason-registry/pull/3899
=> feat: add cortex-debug

packages/cljfmt/package.yaml
should close https://github.com/williamboman/mason.nvim/issues/1641
=> feat: add cljfmt

packages/css-variables-language-server/package.yaml
https://github.com/vunguyentuan/vscode-css-variables
Added to lspconfig here: https://github.com/neovim/nvim-lspconfig/commit/6a62bc113fce2615ebf22be361d27b9e82746e86
=> feat: add css-variables-language-server

packages/jinja-lsp/package.yaml
https://github.com/williamboman/mason.nvim/issues/1636
=> add jinja-lsp

packages/regols/package.yaml, schemas/enums/language.json
Add support for [regols](https://github.com/kitagry/regols). Support exists in [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#regols).
=> feat: add regols

packages/haskell-language-server/package.yaml
I updated hls to the latest and recommended version
=> bump(haskell-language-server): update to version 2.7.0.0

packages/erb-formatter/package.yaml
Hi, just wanted to add a formatter for Ruby's ERB template files.
Thanks for considering this addition.
---
gem: https://rubygems.org/gems/erb-formatter
ERB ref: https://github.com/ruby/erb
=> feat: add erb-formatter

packages/findent/package.yaml
This PR adds specification of the findent Fortran code formatter.
PyPI: https://pypi.org/project/findent/
GitHub: https://github.com/gnikit/findent-pypi
=> feat: add specification of the findent Fortran formatter

packages/fprettify/package.yaml
This PR adds specification of the fprettify Fortran code formatter.
PyPI: https://pypi.org/project/fprettify/
GitHub: https://github.com/pseewald/fprettify
=> feat: add specification of the fprettify Fortran formatter

packages/tinymist/package.yaml
=> feat: Add tinymist

.github/pull_request_template.md, CONTRIBUTING.md
- **docs(contributing): add Open VSX section**
- **docs(contributing): add testing section**
- **chore: add pull request template**
=> docs: update contributing and add pull request template

packages/erb-formatter/package.yaml
=> fix(erb-formatter): fix bin name

packages/nimlangserver/package.yaml
=> feat(nimlangserver): target stable releases and use release assets

packages/ruff/package.yaml
Missed out on updating the description in the previous PR https://github.com/mason-org/mason-registry/pull/4818
=> chore: update ruff's description to include formatter

packages/markdown-oxide/package.yaml
Are the platforms typical? How does this look at @williamboman
=> Support markdown oxide binaries

packages/gitlab-ci-ls/package.yaml
Added Gitlab CI language server.
=> feat(gitlab-ci-ls): added

packages/zk/package.yaml
The main repos for the zk tools have been migrated to the zk-org organisation a while ago. The old repository no longer has any releases so mason fails to pull the zk package.
#4267
=> Update zk URL

packages/starpls/package.yaml
Adding new lsp for bazel/starlark files https://github.com/withered-magic/starpls it's already added to nvim-lspconfig as well
=> add starpls

packages/earthlyls/package.yaml, schemas/enums/language.json
add the configuration to download earthlyls binaries from the github release
related to https://github.com/neovim/nvim-lspconfig/pull/3111
=> add earthlyls configuration

packages/markdown-oxide/package.yaml
https://github.com/Feel-ix-343/markdown-oxide/issues/77
=> Update markdown oxide package

packages/motoko-lsp/package.yaml, schemas/enums/language.json
Add the official language server for the Motoko programming language.
=> feat: add motoko-lsp

packages/opa/package.yaml
Adds [`opa`](https://www.openpolicyagent.org/docs/latest/cli/) cli for formatting, linting, building, and running rego files.
=> feat(opa): add open-policy-agent cli

packages/ktfmt/package.yaml
This PR adds [ktfmt](https://github.com/facebook/ktfmt), a program that reformats Kotlin source code to comply with the common community conventions.
=> feat: add ktfmt

packages/svelte-language-server/package.yaml
Similar PR as for astro, but for Svelte.
See rationale [here](https://github.com/mason-org/mason-registry/pull/5924)
=> feat(svelte): add `typescript-svelte-plugin` to `svelte-language-server`

packages/mdsf/package.yaml
Added support for [mdsf](https://crates.io/crates/mdsf), a code formatter for markdown code blocks.
=> feat: add mdsf

packages/sonarlint-language-server/package.yaml
Not semver-compliant 😞 But I'll stick with doing it manually.
=> bump(sonarlint-language-server): update to v4.7.0

packages/jdtls/package.yaml
=> bump(jdtls): update to v1.37

packages/ktfmt/package.yaml
=> bump(ktfmt): v0.51

packages/motoko-lsp/package.yaml
Beep boop. I've updated motoko-lsp to 0.16.4.
=> bump(motoko-lsp): update to 0.16.4

packages/ocaml-lsp/package.yaml
Bump `ocaml-lsp` to `v1.19.0`
https://github.com/ocaml/ocaml-lsp/releases/tag/1.19.0
For might only be merged after https://github.com/mason-org/mason-registry/pull/6622
=> bump(ocaml-lsp): v1.19.0

packages/motoko-lsp/package.yaml
Beep boop. I've updated motoko-lsp to 0.16.6.
=> bump(motoko-lsp): update to 0.16.6

packages/ktfmt/package.yaml
=> bump(ktfmt): update to v0.52

packages/sonarlint-language-server/package.yaml
Not semver-compliant 😞 But I'll stick with doing it manually.
=> bump(sonarlint-language-server): update to v4.9.0

packages/latexindent/package.yaml
Update latexindent to latest version
=> Bump latexindent version

packages/motoko-lsp/package.yaml
Beep boop. I've updated motoko-lsp to 0.16.7.
=> bump(motoko-lsp): update to 0.16.7

packages/sonarlint-language-server/package.yaml
Not semver-compliant 😞 But I'll stick with doing it manually.
=> bump(sonarlint-language-server): update to v4.11.1

packages/jdtls/package.yaml
update jdtls to version 1.40.0
=> bump(jdtls): update to v1.40.0

packages/ols/package.yaml
OLS provides ARM specific releases now, there has also been the addition of a zip based release that bundles some optional assets it can utilise.
=> feat(ols): add arm64 & use zip releases

packages/ktfmt/package.yaml
=> bump(ktfmt): v0.53

packages/haskell-language-server/package.yaml
=> bump(haskell-language-server): Update to version 2.9.0.1

packages/sonarlint-language-server/package.yaml
Update SonarLint language server to version [4.14](https://github.com/SonarSource/sonarlint-vscode/releases/tag/4.14.0%2B77092).
=> bump(sonarlint-language-server): update to v4.14.0

packages/jayvee-language-server/package.yaml
Hi, I'm a student researcher at Friedrich-Alexander-Universität Erlangen-Nürnberg working on the [jayvee language](https://jvalue.github.io/jayvee/). We recently released [v0.5.0](https://github.com/jvalue/jayvee/releases/tag/v0.5.0-alpha) which improves the language server and we would be really happy to see this added to the mason-registry.
=> feat: add jayvee-language-server

packages/motoko-lsp/package.yaml
Beep boop. I've updated motoko-lsp to 0.16.16.
=> bump(motoko-lsp): update to 0.16.16

packages/haxe-language-server/package.yaml
Beep boop. I've updated haxe-language-server to 2.32.2.
=> bump(haxe-language-server): update to 2.32.2

packages/sonarlint-language-server/package.yaml
Update Sonarlint Language Server to version 4.15.0.
=> bump(sonarlint-language-server): update to v4.15.0

packages/ktfmt/package.yaml
=> bump(ktfmt): v0.54

packages/v-analyzer/package.yaml
Updates the v-analyzer version and repo links
#4598
=> feat(v-analyzer): update v-analyzer

packages/typos-lsp/package.yaml
Add `musl` binaries to `typos-lsp` package.
=> feat(typos-lsp): add musl binaries

packages/alejandra/package.yaml
https://github.com/kamadorueda/alejandra
Add [alejandra](https://github.com/kamadorueda/alejandra), a formatter for Nix.
=> feat: add alejandra

packages/tex-fmt/package.yaml
Add tex-fmt formatter for LaTeX files.
=> feat: add tex-fmt

packages/c3-lsp/package.yaml
=> feat: add c3-lsp

packages/buf/package.yaml
Update Buf definition to include an LSP
https://github.com/neovim/nvim-lspconfig/pull/3414
=> feat(buf) buf now supports an LSP

packages/ts_query_ls/package.yaml
Add [ts_query_ls](https://github.com/ribru17/ts_query_ls), an LSP implementation for Tree-sitter's query files
=> feat: ts_query_ls at v1.2.4

packages/typst-lsp/package.yaml
Deprecate typst-lsp
See [deprecation notice](https://github.com/nvarner/typst-lsp?tab=readme-ov-file#deprecation-notice)
=> chore: Add deprecation notice for typst-lsp

packages/sphinx-lint/package.yaml
Linter for stylistic and formal issues in Sphinx documentation
Add [sphinx-lint](https://github.com/sphinx-contrib/sphinx-lint), a linter for stylistic and formal issues in Sphinx documentation.
=> feat: add sphinx-lint

packages/bandit/package.yaml
I added the linter bandit for python. he is already supported in nvim-lint project.
=> feat: add bandit linter for python

packages/neocmakelsp/package.yaml
Use release assets since neocmakelsp provide the binary file, and removes dependency on cargo
=> feat(neocmakelsp): use release assets

packages/copilot-language-server/package.yaml
GitHub has released Copilot Language Server, so add it
release blog: https://github.blog/changelog/2025-02-10-copilot-language-server-sdk-is-now-available
Check operation using [zbirenbaum/copilot.lua](https://github.com/zbirenbaum/copilot.lua)
zbirenbaum/copilot.lua setting
=> feat: add copilot-language-server

packages/sonarlint-language-server/package.yaml
Update Sonarlint Language Server to version 4.16.0.
=> bump(sonarlint-language-server): update to v4.16.0

packages/eugene/package.yaml
Added the `eugene` postgres migration linter.
I can verify it works on x86 linux.
=> feat: add eugene migration linter for postgres

packages/refurb/package.yaml
Adds a package for [refurb](https://github.com/dosisod/refurb), which is a tool for refurbishing and modernizing Python codebases.
I would like to add refurb as a python linter.
I have not created a ticket in advance, because I thought it would be just easier to create the PR, but i can create an issue if this is mandatory.
=> feat: Add refurb

packages/ocaml-lsp/package.yaml, packages/rust_hdl/package.yaml, packages/sleek/package.yaml, packages/superhtml/package.yaml, packages/xcbeautify/package.yaml
I would like to add  [sleek](https://github.com/nrempel/sleek) as a SQL formatter.
=> feat: add sleek, an SQL formatter

packages/prettypst/package.yaml
Adds [prettypst](https://github.com/antonWetzel/prettypst) another formatter for Typst.
As [typst-fmt](https://github.com/astrale-sharp/typstfmt) was archived this is an alternative formatter.
=> feat: add prettypst

packages/bazelrc-lsp/package.yaml
Add bazelrc-lsp, a language server for bazelrc config files
=> feat: add bazelrc-lsp

packages/kulala-fmt/package.yaml
kulala-fmt is an opinionated .http and .rest files linter and formatter.
Add kulala-fmt
https://github.com/mistweaverco/kulala-fmt/issues/12
=> feat: add kulala-fmt

packages/sonarlint-language-server/package.yaml
Update Sonarlint Language Server to version 4.17.0.
=> bump(sonarlint-language-server): update to v4.17.0

packages/cairo-language-server/package.yaml
adds vscode lsp schema from the repo
=> feat(cairo): add vscode lsp schema

packages/angular-language-server/package.yaml
=> feat(angular): add lsp schema

packages/cobol-language-support/package.yaml
adds vscode lsp schema to cobol ls
=> feat(cobol-ls): add lsp schema

packages/ruby-lsp/package.yaml
Adds vscode lsp schema to ruby-lsp
=> feat(ruby-lsp): add vscode lsp schema

packages/sonarlint-language-server/package.yaml
Adds vscode lsp schema to sonarlint
=> feat(sonarlint): add vscode lsp schema

packages/tsp-server/package.yaml
Adds vscode lsp schema to tsp-server
=> feat(tsp): add lsp schema

packages/prisma-language-server/package.yaml
Adds vscode lsp schema to prisma-ls
=> feat(prisma-ls): add lsp schema

packages/groovy-language-server/package.yaml
Adds vscode lsp schema to groovy language server
=> feat(groovy-ls): add vscode lsp schema

packages/asm-lsp/package.yaml
=> feat(asm-lsp): add lsp schema

packages/gitlab-ci-ls/package.yaml
Adds vscode schema to gitlab-ci-ls
=> feat(gitlab-ci-ls): add vscode lsp schema

packages/typos-lsp/package.yaml
Adds vscode schema to typos-lsp
=> feat(typos-lsp): add vscode lsp schema

packages/starlark-rust/package.yaml
Adds vscode lsp schema to starlark-rust
=> feat(starlark-rust): add vscode lsp schema

packages/sqlls/package.yaml
Adds vscode lsp schema to sqlls
=> feat(sqlls): add vscode lsp schema

packages/cpptools/package.yaml
=> feat(cpptools): add vscode lsp schema

packages/m68k-lsp-server/package.yaml
Adds vscode lsp schema to m68k-lsp
=> feat(m68k-lsp): add vscode lsp schema

packages/efm/package.yaml
=> feat(efm): add lsp schema

packages/verible/package.yaml
Adds vscode lsp schema to verible
=> feat(verible): add vscode lsp schema

packages/veryl-ls/package.yaml
Adds vscode lsp schema to veryl
=> feat(veryl): add vscode lsp schema

packages/visualforce-language-server/package.yaml
Adds vscode lsp schema to visualforce language server
=> feat(visualforce): add vscode lsp schema

packages/vscode-java-decompiler/package.yaml
Adds vscode lsp schema to the vscode java decompiler
=> feat(java-decompiler): add vscode lsp schema

packages/yls-yara/package.yaml
Adds vscode lsp schema to yls-yara
=> feat(yls): add vscode lsp schema

packages/zeek-language-server/package.yaml
Adds vscode lsp schema to zeek language server
=> feat(zeek-ls): add vscode lsp schema

packages/solang/package.yaml
=> feat(solang): add vscode lsp schema

packages/rescript-language-server/package.yaml
Adds the vscode lsp schema to rescipt-ls
=> feat(rescript-ls): add vscode lsp schema

packages/raku-navigator/package.yaml
Adds vscode lsp schema to raku navigator
=> feat(raku-navigator): add vscode lsp schema

packages/pico8-ls/package.yaml
Adds vscode lsp schema to pico8-ls
=> feat(pico8-ls): add vscode lsp schema

packages/pest-language-server/package.yaml
Adds vscode lsp schema to pest-ls
=> feat(pest-ls): add vscode lsp schema

packages/ols/package.yaml
=> feat(ols): add vscode lsp schema

packages/nomicfoundation-solidity-language-server/package.yaml
Adds the vscode lsp schema to the nomicfoundation solidity language server
=> feat(nomicfoundation): add vscode lsp schema

packages/motoko-lsp/package.yaml
Adds the vscode lsp schema to motoko-lsp
=> feat(motoko-lsp): add vscode lsp schema

packages/millet/package.yaml
Adds the vscode lsp schema to millet
=> feat(millet): add vscode lsp schema

packages/metamath-zero-lsp/package.yaml
Adds vscode schema to the metamath-zero-lsp
=> feat(metamath-zero-lsp): add vscode lsp schema

packages/jinja-lsp/package.yaml
Adds vscode lsp schema to jinja-lsp
=> feat(jinja-lsp): add vscode lsp schema

packages/custom-elements-languageserver/package.yaml
Adds vscode lsp schema to custom-elements-languageserver
=> feat(custom-elements-ls): add vscode lsp schema

packages/sqruff/package.yaml
Adding https://github.com/quarylabs/sqruff which will be downloaded via cargo.
(Configured using https://github.com/nvimtools/none-ls.nvim/pull/212).
=> feat: Add `sqruff`

packages/rpmlint/package.yaml
=> feat: add rpmlint

packages/nginx-config-formatter/package.yaml
Adds the nginx-config-formatter
=> feat: add nginx-config-formatter

packages/ltex-ls-plus/package.yaml
Add `ltex-ls-plus` package. Supersedes #7974, after @chrisgrieser asked for it to be reopened.
=> feat: ltex-ls-plus

packages/pkl-lsp/package.yaml
This adds the relatively new official [pkl-lsp](https://github.com/apple/pkl-lsp) directly from Apple.
=> feat: add pkl-lsp

packages/gh-actions-language-server/package.yaml
Add language server for GitHub actions.
external: https://github.com/lttb/gh-actions-language-server/issues/1
=> feat: add gh-actions-language-server for GitHub Actions/Workflows

packages/typstyle/package.yaml
add typstyle, a formatter for the typst language
=> feat: add typstyle

packages/robotcode/package.yaml
Added a package for the [robotcode ](https://robotcode.io/) language server and debugger, used with [Robot Framework](https://robotframework.org/).
Note that the other package robotframework_lsp from robocorp is [no longer being maintained](https://github.com/robocorp/robotframework-lsp/issues/1051) and [robotcode has taken over as the tool of choice for vscode](https://docs.robotframework.org/docs/getting_started/ide#visual-studio-code).
=> Added robotcode LSP and DAP package

packages/postgrestools/package.yaml
=> fix(postgrestools): repo was renamed

packages/vhdl-style-guide/package.yaml, packages/vsg/package.yaml
Add vsg formatter for VHDL files
=> feat: add vsg formatter

packages/api-linter/package.yaml
This PR adds the api-linter binary: https://github.com/googleapis/api-linter
=> feat(linter): api-linter

packages/emmylua_ls/package.yaml
Adds bins to emmylua_ls so to have them for the bin section
#9477
=> feat(emmylua): add emmylua bins to assets

packages/local-lua-debugger-vscode/package.yaml
Add `local-lua-debugger-vscode`
=> feat: Add local-lua-debugger-vscode

packages/mypy/package.yaml
Adds the other mypy binaries shipped with the package
#9498
=> feat(mypy): add other mypy binaries

packages/buf-language-server/package.yaml
=> feat(buf-ls): add deprecation warning to buf-ls

.github/pull_request_template.md, CONTRIBUTING.md
See discussion here:
https://github.com/orgs/mason-org/discussions/2#discussioncomment-12615405
=> docs: add requirements for new packages

packages/clang-format/package.yaml
=> feat(clang-format): add additional binaries

packages/sqruff/package.yaml
=> feat(sqruff): use release assets

packages/ntt/package.yaml
Adds the ntt tool from Nokia
It's in [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#ntt)
=> feat: add ntt

packages/wasm-language-tools/package.yaml
Adds wasm-language-tools
Is in [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#wasm_language_tools)
=> feat: add wasm-language-tools

packages/pgformatter/package.yaml
Adds [pgformatter](https://github.com/darold/pgFormatter), a PostgreSQL SQL syntax beautifier.
1.8k stars on GitHub.
=> feat: add pgformatter

packages/just-lsp/package.yaml
Adds the just-lsp by @terror https://github.com/terror/just-lsp
[Added to lspconfig](https://github.com/neovim/nvim-lspconfig/pull/3655)
=> feat: add just-lsp

packages/sith-language-server/package.yaml
Add sith-language-server, an experimental Python language server made in Rust.
=> feat: add sith-language-server

packages/sonarlint-language-server/package.yaml
Update Sonarlint Language Server to version 4.21.0
=> bump(sonarlint-language-server): update to v4.21.0

packages/zk/package.yaml
This should now be resolved via https://github.com/zk-org/zk/pull/540.
=> chore(zk): remove ci_skip entries

packages/tabby-agent/package.yaml, packages/tabby-ml/package.yaml
Adding the [tabby](https://github.com/TabbyML/tabby) LSP.
https://github.com/williamboman/mason.nvim/discussions/1360
Already exists in [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs/tabby_ml.lua).
=> feat: add tabby-agent

.github/pull_request_template.md
add reminder to add `neovim.lspconfig` to PR template. follow up to #9774
=> chore: add reminder to add `neovim.lspconfig` to PR template

packages/java-test/package.yaml
=> bump(java-test): 0.43.1

packages/sonarlint-language-server/package.yaml
Update Sonarlint Language Server to version 4.22.0
=> bump(sonarlint-language-server): update to v4.22.0

packages/ty/package.yaml
Update ty package to the latest version.
PD: Sorry if these kind of updates are done by the bot 🙏🏼
=> feat: update ty package

packages/mmdc/package.yaml
Adds `mmdc` (mermaid cli) package to the registry.
Closes #10418
[mermaid cli](https://github.com/mermaid-js/mermaid-cli) project has >3k stars and is actively maintained (last release was <24 hours ago)
=> feat(mmdc): add mmdc

packages/tombi/package.yaml
Adds tombi to packages.
https://github.com/tombi-toml/tombi
=> feat: add tombi

packages/herb-language-server/package.yaml
This pull request adds the [Herb](https://github.com/marcoroth/herb) [Language Server](https://herb-tools.dev/projects/language-server). This language server is designed to operate on HTML+ERB (`*.html.erb`) files.
\-
* [`nvim-lspconfig` pull request](https://github.com/neovim/nvim-lspconfig/pull/3925)
* [100+ stars on `marcoroth/herb`](https://github.com/marcoroth/herb)
---
Let me know if you need to me tweak anything, thank you for maintaining this awesome project! 🙌🏼
=> feat(herb-language-server): Add Herb Language Server (HTML+ERB files)

packages/fennel-ls/package.yaml
See the `fennel-ls` package on Luarocks for available versions:
https://luarocks.org/modules/xerool/fennel-ls
=> bump(fennel-ls): from 0.1.3-4 to 0.2.1-1

packages/kotlin-lsp/package.yaml
Version update to match [new release](https://github.com/Kotlin/kotlin-lsp/releases/tag/kotlin-lsp%2Fv0.253.10629) in upstream repo
=> bump(kotlin-lsp): update to v0.253.10629

packages/laravel-ls/package.yaml
Not sure why it is not auto updated by the CLI tool, but this commit updates the package to the latest version.
=> bump(laravel-ls): Update to v0.0.10

packages/laravel-ls/package.yaml
Add windows binary from github releases
=> feat(laravel-ls): add windows binary.

packages/laravel-ls/package.yaml
Fixed the homepage URL to Github for the laravel-ls package.
=> Fix homepage link for laravel-ls

packages/jdtls/package.yaml
Tested for 9 days in production ;)
=> bump(jdtls): update to v1.50.0

packages/superhtml/package.yaml
includes changes to the release format
=> update superhtml to v0.6.0
