mason-org/mason-registry

renovate.json5
Package definitions are entirely independent of one another, no need to
ensure branches are up to date.
=> chore(renovate): set rebaseWhen: "conflicted"

.github/workflows/package-tests.yaml
This doesn't really serve any purpose, running on PRs is enough.
=> chore(workflows): dont run package tests on push

packages/shopify-theme-check/package.yaml, packages/slint-lsp/package.yaml, packages/smithy-language-server/package.yaml, packages/solang/package.yaml, packages/solargraph/package.yaml, packages/solhint/package.yaml, packages/solidity-ls/package.yaml, packages/solidity/package.yaml, packages/sorbet/package.yaml, schemas/components/sources/gem.json, schemas/components/sources/github/release.json, schemas/enums/language.json
Adds:
- shopify-theme-check
- slint-lsp
- smithy-language-server
- solang
- solargraph
- solhint
- solidity
- solidity-ls
- sorbet
=> feat: add more packages

renovate.json5
Reverts mason-org/mason-registry#160
renovate seems to be running updated version where this helper is included now
=> chore(renovate): update commitMessage

packages/zk/package.yaml, schemas/components/sources/github/release.json
This mechanism applies to all sources, not just GitHub releases, so the JSON schema is not entirely correct (it only accepts `version_overrides` for GitHub release sources), but I decided I don't care.
=> feat: add ability to override source definition for historic version ranges

packages/markdown-toc/package.yaml
`null-ls.nvim` contains `markdown_toc` BUILTIN,
while `mason.nvim` does not provide a source.
Ref: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#markdown_toc
=> feat: add markdown-toc

packages/js-debug-adapter/package.yaml
See https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#vscode-js-debug which uses the dapServer instead of the vsDebugServer
=> feat(js-debug-adapter): add dap server alias

packages/groovy-language-server/package.yaml, renovate.json5
This is a headache to debug (I'm reviewing the source code of renovate to figure this out step by step).
=> fix(renovate): set empty currentValue if updating git-refs digests

packages/helm-ls/package.yaml, packages/helm_ls/package.yaml, schemas/enums/language.json
i found an early state project, that provide a Language server for Helm file.
even if it's in early dev, it work really good.
would be good to have this LSP in Mason.
especially for DevOps ppl.
=> feat: add helm-ls

packages/netcoredbg/package.yaml
Added x64 as valid arch for linux (pre-built release)
=> feat(netcoredbg): Update package.yaml to include linux x64 arch

packages/tfsec/package.yaml
This adds `tfsec` to the mason registry, used by `null-ls`.
I'm unsure how to test this locally so beware. :)
=> feat: add tfsec

packages/haskell-debug-adapter/package.yaml
Hi there,
I took some time to put together this port of [phoityne/haskell-debug-adapter](https://github.com/phoityne/haskell-debug-adapter).
I would love for any feedback and/or criticisms so that I can improve the.
Like the haskell-language-server package, haskell-debug-adapter is dependent on ghcup. The package uses ghcup to install a local copy of stack. Stack is then used to build local versions of haskell-dap, ghci-dap, and finally haskell-debug-adapter.
I was unable to test my the windows implementation as I do not have a windows machine with me at the moment. I would greatly appreciate anyone who would be able to test this.
=> feat: Add debug-adapter-haskell

packages/taplo/package.yaml
Closes https://github.com/williamboman/mason.nvim/issues/1266.
=> feat(taplo): add Windows targets

packages/staticcheck/package.yaml
See https://github.com/dominikh/go-tools/releases for information about the last several releases
Also worth noting, staticcheck changed the format of it's release names: https://github.com/dominikh/go-tools#releases
=> bump(staticcheck): update to 2023.1.3 (v0.4.3)

packages/omnisharp-mono/package.yaml
Closes https://github.com/williamboman/mason.nvim/issues/1280.
=> fix(omnisharp-mono): add bin entry

packages/texlab/package.yaml
On ARM64 linux, texlab is not installable, while packages exist in github. This PR adds support for linux ARM64.
=> feat: add texlab on arm64 linux

packages/docformatter/package.yaml, packages/pyment/package.yaml
Pull request to add two of the major Python docstring formatting packages to the mason registry, namely:
- [docformatter](https://pypi.org/project/docformatter/), and
- [pyment](https://pypi.org/project/pyment/).
Both packages provide functionality to format docstrings in Python files, with each package providing relative advantages/disadvantages over the other. I expect development pace to vary between the two and that mason users require the option to select a formatter that suits their project's needs. The closest existing package in the [mason registry](https://mason-registry.dev/registry/list) is pydocstyle, however, that package only provides PEP 257 compliance checking, not formatting.
The added package.yaml files follow the package definition scheme, and have been created in …
=> Pull request to add Python docstring formatters

packages/salt-lsp/package.yaml
Closes https://github.com/williamboman/mason.nvim/issues/1301.
=> fix(salt-lsp): link correct bin name

packages/java-language-server/package.yaml
Fixes https://github.com/williamboman/mason.nvim/issues/1318.
=> fix(java-language-server): use exec wrappers

packages/luacheck/package.yaml
The download source for luacheck is luarocks, for which homepage is the new one
See <https://luarocks.org/modules/lunarmodules/luacheck>
=> fix(luacheck): update homepage link

renovate.json5
Hopefully reduces the amount of work done by Renovate.
=> chore(renovate): explicitly set managers

packages/helm-ls/package.yaml
It was using invalid helm-ls version. Version 0.0.4 does not exist.
=> bump(helm-ls): downgrade to 0.0.3

packages/vue-language-server/package.yaml, renovate.json5
Dependency bot doesn't seem to be pulling in the "pre-release" changes in, for volar, but was manually moved to point to 1.7 due to  package name change. Need to update to latest to fix issues with typescript 5.1.3
=> chore: update vue-language-server

renovate.json5
Seems like the "latest" tag is now pointing to the latest version.
=> chore(renovate): remove packageRule for vue-language-server

packages/haskell-language-server/package.yaml
Not sure why this hasn't been automatically updated, but I recently updated my Mason dependencies and noticed that it downgraded my installed version of HLS. I've temporarily solved this by manually installing it via GHCup, but would prefer for it to work here.
=> bump(haskell-language-server): update to v2.0.0.0

packages/emmet-language-server/package.yaml
Hey! This PR adds a new language server called `emmet-language-server` (an alternative to aca/emmet-ls which already exists in the registry) to the registry.
([repo](https://github.com/olrtg/emmet-language-server))
I wanted to ask also.. if you decide to merge this can you take a careful look to the following (since it's my first time doing this and the `source` and `bin` properties were confusing to me):
- The [package in npm](https://www.npmjs.com/package/@olrtg/emmet-language-server) is under `@olrtg/emmet-language-server`
- The command can be called just with `emmet-language-server`
=> feat: add emmet-language-server

packages/mdformat/package.yaml
[`mdformat`](https://github.com/executablebooks/mdformat) is a Markdown formatter written in Python that is extensible using plugins.
=> feat: add mdformat

packages/angular-language-server/package.yaml
Fixes https://github.com/williamboman/mason.nvim/issues/1404.
=> fix(angular-language-server): pin typescript to 4.8.2

packages/vscode-java-decompiler/package.yaml
Just saw https://github.com/williamboman/mason.nvim/issues/193 and decided to try to make a package for it.
**Some notes:**
Since the [vscode-java-decompiler](https://github.com/dgileadi/vscode-java-decompiler) repository has the required `jar` files already committed in, I have left the `run` empty since it's required by the `yaml` spec.
Tried the workflow on my fork and it seems to pass the tests. Although admittedly, I don't know how to test this out on my local machine.
=> feat: add vscode-java-decompiler jars.

packages/semgrep/package.yaml
Closes https://github.com/williamboman/mason.nvim/issues/1418.
=> fix(semgrep): also link pysemgrep executable

packages/ripper-tags/package.yaml
Add [ripper-tags](https://github.com/tmm1/ripper-tags) gem which is used to generate ctags for Ruby file types.
**Help Wanted:**
I'm unsure how I can test this. I thought I could add my fork as a registry but I'm getting this error:
```
Uninstalled registries
Packages from the following registries are unavailable. Press C to install.
- github.com/wassimk/mason-registry [uninstalled]
Registry installation failed with the following error:
GitHubRegistrySource(repo=wassimk/mason-registry) failed to install: Failed to download registry archive.
```
=> feat: add ripper-tags

packages/pico8-ls/package.yaml, schemas/enums/language.json
Adding support for PICO-8 by using https://github.com/japhib/pico8-ls/
Solves https://github.com/japhib/pico8-ls/issues/34
Related - git tags needed in pico8-ls for better renovate support https://github.com/japhib/pico8-ls/issues/45
=> feat: add pico8-ls

packages/ruff-lsp/package.yaml, packages/ruff/package.yaml
These are now hosted under the astral-sh org on GitHub.
=> chore(ruff,ruff-lsp): update homepage links

packages/zls/package.yaml
Fixes #2430. This is supposed to improve DX and performance when using zls in neovim.
=> chore(zls): update lsp schema location

packages/zls/package.yaml
Changed version number for the `zls` package to the latest (0.11.0). Latest package source archives no longer use zstd and are now packaged in gzipped tarballs and `.zip` files on Windows.
Also removed the `ci_skip` entries, as they were added there because the source archives where `.tar.zst`.
=> bump(zls): update to v0.11.0

packages/angular-language-server/package.yaml
Otherwise language server fails to start with following error:
```
"rpc"	"ngserver"	"stderr"	"/home/user/.local/share/nvim/mason/packages/angular-language-server/node_modules/@angular/language-server/index.js:235\n      throw new Error(`Failed to resolve '${packageName}' with minimum version '${minVersion}' from ` + JSON.stringify(probeLocations, null, 2));
```
Plus it's specified in language-server's release notes (via #2398):
> Update the bundled version of TypeScript to 5.1.3
=> fix(angular-language-server): outdated typescript version for v16.1.8

packages/nil/package.yaml
First of all, I am very happy with Mason. Thanks for this package!
I noticed that the Nil language for server is incompatible with newer versions of Nix. When building the version from Mason it fails. The fix incorporated in this newer version and should be backwards compatible. See oxalica/nil#93 for more context.
This also bumps to the latest version. There are more tags possible, I just picked the latest version of the language server. The tags are listed here: [oxalica/nil/tags](https://github.com/oxalica/nil/tags)
EDIT: I see I mistakenly tagged a PR in my commit message 🙃, I'll edit that on merge.
=> bump(nil): update to 2023-08-09

packages/biome/package.yaml, packages/rome/package.yaml
rome is unmaintained, and biome is the fork/successor to it. See: https://biomejs.dev/blog/annoucing-biome
Closes https://github.com/williamboman/mason.nvim/issues/1482
=> packages: add `biome` and update `rome`

packages/zls/package.yaml
Closes https://github.com/williamboman/mason.nvim/issues/1496.
=> fix(zls): add version overrides

packages/meson-language-server/package.yaml, packages/swift-mesonlsp/package.yaml, schemas/enums/language.json
Adds [Swift-MesonLSP](https://github.com/JCWasmx86/Swift-MesonLSP), a language server for the meson build system.
=> feat: add swift-mesonlsp

packages/efm/package.yaml
Previously, efm was installed via the golang package manager. However, not all users will have the `go` executable installed on their machines.
Latest release: https://github.com/mattn/efm-langserver/releases/tag/v0.0.48
=> feat: fetch efm binaries from github

packages/darker/package.yaml
[darker](https://github.com/akaihola/darker) runs [black](https://github.com/psf/black) only on the changed lines in a git repo. Useful in situations where the whole repo hasn't been painted black for one reason or another but you still want to be able to run autoformatter on changes you made.
=> feat: add darker

packages/cfn-lint/package.yaml
**CloudFormation** Linter.
https://github.com/aws-cloudformation/cfn-lint
=> fix(cfn-lint): add missing language

packages/easy-coding-standard/package.yaml
Sorry for bumping, I've accidentally closed #2804 
There was a [problem](https://github.com/mason-org/mason-registry/actions/runs/6240396709/attempts/2) with test for win x64
Only two packages in registry use composer so far
`phpactor` - has only support for unix
`psalm` having same problem (see #1209) as `easy-coding-standard`
=> add easy-coding-standard

packages/rescript-language-server/package.yaml, packages/rescript-lsp/package.yaml
The ReScript Language Server is available on NPM
https://github.com/rescript-lang/rescript-vscode/tree/master/server
Deprecated `rescript-lsp`
=> add rescript-language-server npm package

packages/nilaway/package.yaml
[nilaway](https://github.com/uber-go/nilaway) is a static analysis tool that tries to catch nil panic errors in Go.
=> Add nilaway linter

packages/typos/package.yaml
So `typos` [does not have a dedicated built for arm64](https://github.com/crate-ci/typos/issues/828), but it does work fine on my arm64 machine. 
So I suppose it wouldn't hurt to enable installing it via mason, even if it is not optimized? (Only added support for mac in this PR, since I do not have a linux/windows device and therefore cannot confirm that `typos` works there as well.)
=> add darwin arm64 for `typos`

packages/biome/package.yaml
I noticed `biome` updates being stuck (https://github.com/mason-org/mason-registry/pull/3593). 
A closer look revealed the tests failed, cause the LSP-Json-schema could not be found. That json file has been moved to a new repository with this PR https://github.com/biomejs/biome/pull/819
---
This PR fixes the location of the LSP-Json-schema which is preventing mason from updating biome to 1.4+.
(I also bumped the biome version manually to 1.4.1 to speed things up, but feel free to leave out this commit, if the automated bumping is preferable for some reason.)
=> fix(biome): LSP-json-schema location, which is blocking any update to `biome`

packages/shellcheck/package.yaml
The current repository for `shellcheck` only provides `x86_x64` versions on MacOS.
Switch to using [vscode-shellcheck/shellcheck-binaries](github.com/vscode-shellcheck/shellcheck-binaries) which provides same binaries as upstream + native binaries for Apple silicon based Macs.
=> fix(shellcheck): Use native arm64 binary on darwin

packages/staticcheck/package.yaml
Currently used version is several months old and the latest is `v0.4.6`.
Package docs for reference: https://pkg.go.dev/honnef.co/go/tools@v0.4.6/cmd/staticcheck?tab=versions
=> bump(staticcheck): update to v0.4.6

packages/htmlhint/package.yaml
I am aware that the mason registry already has html linters such as markuplint, however I have found htmlhint to be the easiest to use. I think it would integrate really nicely with plugins like nvim-lint, as the binary file seems to work right out of the box.
=> feat: Add htmlhint

packages/beancount-language-server/package.yaml
`cargo install --locked --force beancount-language-server` is broken due to broken dependencies in newer rust versions:
```
Updating crates.io index
Installing beancount-language-server v1.3.1
Updating crates.io index
warning: package `bumpalo v3.12.1` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
warning: package `hermit-abi v0.3.1` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
Updating crates.io index
Compiling proc-macro2 v1.0.56
Compiling libc v0.2.142
Compiling unicode-ident v1.0.8
Compiling quote v1.0.26
Compiling cfg-if v1.0.0
Compiling autocfg v1.1.0
Compiling memchr v2.5.0
Compiling serde_derive v1.0.160
Compiling io-lifetimes v1.0.10
Compiling once_cell v1.17.1
Compiling serde v1.0.160
Compiling rustix …
```
=> Install beancount-language-server without --locked

packages/elixir-ls/package.yaml
This is an attempt to reconcile the issues raised in #3910.
I have been unable to configure my mason installation in a way that uses my forked registry, so I'm unclear on whether any other change needs to be made to allow this to work.
=> Update elixir-ls to v0.18.1 with update to debugger

packages/java-debug-adapter/package.yaml, packages/java-test/package.yaml
Closes https://github.com/mason-org/mason-registry/issues/3766.
Closes https://github.com/mason-org/mason-registry/issues/3036.
=> chore: use openvsx source for java-test and java-debug-adapter

packages/erlang-debugger/package.yaml, packages/erlang-ls/package.yaml
The debugger has been extracted from the Erlang LS repository, so it can be used in combination with other language servers (e.g. [ELP](https://github.com/mason-org/mason-registry/tree/main/packages/elp)). This PR (completely untested since I don't use Vim myself) adds a new package for the DAP debugger and removes the DAP parts from Erlang LS.
=> Decouple Erlang Language Server and Debugger

packages/quick-lint-js/package.yaml
Since version 3.0.0 quick-lint-js also supports typescript.
=> feat: Add typescript to quick-lint-js

packages/jdtls/package.yaml
https://download.eclipse.org/jdtls/milestones/1.31.0/latest.txt
```
$ tar -tvf ~/Downloads/jdt-language-server-1.31.0-202401111522.tar.gz | grep equinox.launcher_
-rwxr-xr-x jenkins/1001380000   56356 2024-01-11 10:26 plugins/org.eclipse.equinox.launcher_1.6.700.v20231214-2017.jar
```
=> Update jdt.ls version suffixes

packages/stylua/package.yaml
Hi and thank you for mason project
Thanks to @JohnnyMorganz availability from `stylua` [v0.20.0](https://github.com/JohnnyMorganz/StyLua/releases/tag/v0.20.0) (in mason registry already bumped here #4223) a new release artifact was added to support amd64 linux musl
This PR updates `stylua` package manifest in mason registry to incorporate this change
=> feat(stylua): add new linux_x64_musl target

packages/sqls/package.yaml
The original sqls repo was archived, with future development moved into the github.com/sqls-server GitHub org. 
This PR:
* Updates mason-registry to use https://github.com/sqls-server/sqls instead of https://github.com/lighttiger2505/sqls.
* Version bumps `sqls` from `v0.2.22` to `v0.2.27`.
=> feat: sqls repo was moved. re-point it in mason-registry

packages/salt-lint/package.yaml
PR to add the `salt-lint` linter for Salt / SaltStack.
https://github.com/warpnet/salt-lint
I'm not clear on how to test this yet, but it looks like opening a PR will trigger some CI tests.
Note: `salt-lint` is one of the linters supported by [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) ( in [lua/null-ls/builtins/diagnostics/saltlint.lua](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics/saltlint.lua) ).  I'll also be submitting a PR to add support to [nvim-lint](https://github.com/mfussenegger/nvim-lint).
Thanks!
=> feat: add salt-lint

packages/hclfmt/package.yaml, schemas/enums/language.json
A tool to format files written in the HashiCorp Configuration Language.
=> feat: add hclfmt

packages/ltex-ls/package.yaml
The main intent is to remove the external dependency on a JRE, thus fixing: https://github.com/williamboman/mason.nvim/issues/1531 & https://github.com/valentjn/ltex-ls/issues/187
Implements #2837, but also for mac. Linux still uses the platform-independent release, [to ensure compatibility with arm64](https://github.com/mason-org/mason-registry/pull/2837#pullrequestreview-1686482498).
=> fix(ltex): use platform-specific releases for win/mac

packages/codelldb/package.yaml
The Codelldb debug adapter works with zig along with c, c++, and rust. This PR makes it explicit that codelldb works with zig
=> Add zig to codelldb language list

packages/harper-ls/package.yaml
Hey. I've been working on an English grammar checker called Harper.
I've recently gotten approval to add `harper-ls` (the LSP frontend) to `nvim-lspconfig`. However, I've found that many users find lack of Mason support a significant deterrent, so I'd like to add it to the registry.
I wrote the `package.yaml` in reference to `rust-analyzer/package.yaml`, and I believe it is spec-compliant.
You can find out more about it [here](https://github.com/chilipepperhott/harper).
Thank you for your consideration.
=> feat: add harper-ls

packages/systemdlint/package.yaml, schemas/enums/language.json
Added the `systemdlint` linter from: https://github.com/priv-kweihmann/systemdlint
The language supported here (in (n)vim terms anyway) is `systemd`, though I did not see it in the schema - do you want me to add it to the schema, or should I leave the `language` field empty?
=> [feat]: added systemdlint linter

packages/ruff/package.yaml
ruff is also a formatter and should appear under both the Linter and Formatter category.
ref: https://docs.astral.sh/ruff/formatter/
=> categorise ruff as a linter and formatter

packages/verible/package.yaml
Previously no support for macOS targets outside of [homebrew-verible](https://github.com/chipsalliance/homebrew-verible/tree/main). Tested binaries on M3 MacBook.
=> Add verible macOS binaries for both x86_64 and aarch64 Apple silicon

packages/npm-groovy-lint/package.yaml
Hey i've seen that there is a help wanted label in the mason repo regarding the williamboman/mason.nvim#760 issue, and i also happen to use the npm-groovy-lint for formatting my Jenkinsfile
I have made the package.yaml by referencing the yaml-language-server package as it is also a npm package and by using the schema provided i believe the package.yaml already comply, but feel free to point out if there is something wrong with the package.yaml as this is my first time contributing to this repo.
Thankyou.
=> feat: add npm-groovy-lint

packages/markdown-oxide/package.yaml
Related to https://github.com/Feel-ix-343/markdown-oxide/issues/1
=> Add support for Markdown Oxide

packages/fennel-ls/package.yaml
Adds fennel-ls language server
=> feat: add fennel-ls

packages/deno/package.yaml
Deno v1.40.3 and above now supports aarch64 on Linux
=> Added deno arm64 target

packages/ocamlearlybird/package.yaml
Adds Ocaml DAP `ocamlearlybird` https://github.com/hackwaly/ocamlearlybird. Release https://github.com/hackwaly/ocamlearlybird/releases/tag/1.3.2.
Added setup description to [nvim-dap](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#ocaml-earlybird).
=> feat: add ocamlearlybird

packages/phpcbf/package.yaml, packages/phpcs/package.yaml
PHP_CodeSniffer development is abandoned in squizlabs repository (https://github.com/squizlabs/PHP_CodeSniffer), but continues under PHPCSStandards repository (https://github.com/PHPCSStandards/PHP_CodeSniffer).
This PR only updates the source and doesn't update the version, squizlabs is still on version 3.7.2 but the updated repository is on version 3.9.0. I chose to not update the version to minimize the possible impact of this PR.
=> feat(php_codesniffer): update repository location

packages/basedpyright/package.yaml
BasedPyright is a fork of the pyright project aiming to implement further features not included in the original project.
Those features include functionality deliberately left out of Pyright in favor of Microsoft's closed source project Pylance.
=> feat: add basedpyright

packages/ginko_ls/package.yaml, schemas/enums/language.json
Adds a registry entry for [`ginko_ls`](https://github.com/Schottkyc137/ginko), which is a Device Tree (DTS) Parser and language server. It's very early stages right now, but it's functional. I will also be working on a PR in `nvim-lspconfig` to have a built in configuration for this, as I am currently using a custom defined one.
I tested with the example that the Ginko readme provides. 
```dts
/dts-v1/;
/ {
pic@10000000 {
phandle = <1>;
interrupt-controller;
reg = <0x10000000 0x100>;
}
};
```
In order to configure the LSP, I added this to my nvim configs
```lua
if not configs.ginko_ls then
configs.ginko_ls = {
default_config = {
cmd = { "ginko_ls" };
filetypes = { "dts" };
root_dir = function (_)
return vim.fs.dirname(vim.fs.find({ '.git' }, { upward = true })[1]);
end,
settings = {};
}; …
```
=> Adds ginko registry entry

renovate.json5
This package has been deprecated and is replaced by rescript-language-server.
=> chore(renovate): ignore rescript-lsp

packages/jdtls/package.yaml
I noticed that the automatic version bumping did not correctly update the URL for the archive so I made the small adjustment by hand.
[Source](https://download.eclipse.org/jdtls/milestones/1.34.0/latest.txt)
If accepted then this [PR](https://github.com/mason-org/mason-registry/pull/5225) could be closed.
I have not done any of those since it's a simple version bump and there are GH Actions in place.
=> Update Jdtls to 1.34

packages/tectonic/package.yaml
I just updated tectonic to the latest release. I'm not sure why the renovate bot isn't picking it up, it seems like the last bump was done manually too.
=> bump(tectonic): update version to 0.15.0

packages/ruff/package.yaml
ruff now has experimental LSP support and should appear under this category.
- https://github.com/astral-sh/ruff/pull/10158
- https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ruff
=> add LSP category to ruff

packages/ansible-language-server/package.yaml
Updating the homepage for the `ansible-language-server` to the latest URL, as the currently stated URL points to an archived repository (whose repo description also now points to the latest URL as introduced by this change).
This can be further verified at the package's registry page here: https://www.npmjs.com/package/@ansible/ansible-language-server
=> docs: update ansible-language-server homepage url

packages/ansible-language-server/package.yaml, renovate.json5
Redhat devs are working on incorporating [ansible-language-server](https://github.com/ansible/ansible-language-server) in [vscode-ansible](https://github.com/ansible/vscode-ansible) repo.
Latest version is broken. Reverting it while they fix the issue would allow us to have a working version available through mason without too much config.
https://github.com/ansible/vscode-ansible/issues/1266
=> Revert ansible-language-server to working version 1.2.1

packages/pylyzer/package.yaml
Use github releases instead of `cargo`. This has the advantage that users do not require the rust toolchain to install this package.
=> feat(pylyzer): use github releases instead of `cargo`

packages/zls/package.yaml
Updated version to 0.12.0
- looks like the zls binaries are no longer in a bin subdir but at the root of the archive.
- Also added an overrride for 0.11.0
- archive format for linux and macos has changed to `tar.xz`
=> bump-fix(zls): update to v0.12.0

packages/lua-language-server/package.yaml
Restore linux_arm64_gnu target as the related lua-language-server build is fixed in v3.9.0.
The target was removed because linux-arm64 package was missing in v3.8.0 and v3.8.3 (#5434).
=> feat(lua-language-server): restore linux_arm64_gnu target for v3.9.0

packages/termux-language-server/package.yaml
as per #3646, pkgbuild-language-server was wiped from the internet. The successor to that is termux-language-server. It adds several other file formats other then a PKGBUILD. This PR adds that LSP and I recommend deprecating or removing pkgbuild-language-server.
=> feat: add termux-language-server

packages/astro-language-server/package.yaml
Support for importing astro files in a typescript file needs to be setup by adding the `@astrojs/ts-plugin` as a plugin to `tsserver` or `vtsls`.
The `@astrojs/ts-plugin` has been added as an extra package, so that it's easy to add this to `vtsls`.
See https://github.com/withastro/language-tools/tree/main/packages/ts-plugin
The plugin is part of the overall astro language tools that also includes the astro language server.
A similar thing is needed for vue projects, but luckily the ts plugin is already part of the volar package.
=> feat(astro): add `@astrojs/ts-plugin` as extra package to `astro-language-server`

packages/cobol-language-support/package.yaml
Reverts mason-org/mason-registry#5675
=> bump(cobol-language-support): downgrade to v2.1.1

packages/autotools-language-server/package.yaml, renovate.json5
Downgrade `autotools-language-server` from `0.0.19` to `0.0.18`.
See issue for explanation as to why.
https://github.com/mason-org/mason-registry/issues/6049
=> fix: downgrade autotools-language-server from 0.0.19 to 0.0.18

packages/bacon-ls/package.yaml, packages/bacon/package.yaml
Add support for [bacon](https://dystroy.org/bacon/) and [bacon-ls](https://github.com/crisidev/bacon-ls) ([blog post](https://lmno.lol/crisidev/bacon-language-server)).
It is already supported by [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/pull/3160).
=> feat: add bacon and bacon-ls

packages/zls/package.yaml
The LSP config options for [ZLS](https://github.com/zigtools/zls) are currently provided by using the [package.json](https://github.com/ziglang/vscode-zig/blob/master/package.json) from the [vscode-zig](https://github.com/ziglang/vscode-zig) extension. This has some unfortunate issues:
- some config options are not related to ZLS
- the names don't match since vscode-zig converts them to camelCase
- the default values may be different (e.g `semantic_tokens` is `"partial"` in vscode-zig)
ZLS does provide a [json schema](https://github.com/zigtools/zls/blob/master/schema.json) for all of its configuration options so there is no need to depend on anything else. And it obviously matches exactly what ZLS provides.
=> fix(zls): use lsp config schema from ZLS instead of vscode-zig

packages/rust_hdl/package.yaml
rust_hdl installation instructions did not include the libraries required
https://github.com/mason-org/mason-registry/issues/6139
=> Fix: Correct rust_hdl library installation

packages/angular-language-server/package.yaml
I having trouble on angulals v18, it will exit with error looking for a file named ngtypecheck.ts and I want to other lts version of angularls and it is not available on the registery, the latest version after v18 is v14. With this pull request I added lts version from v9 to v17
Just for a reference there is an open issue open 4 days ago (Jun 24, 2024)
https://github.com/angular/vscode-ng-language-service/issues/2043
=> feat: angularls 1 major version per version on version_overrides

packages/java-test/package.yaml
Current version doesn't work with jdt-ls 1.37.0
java-test to 0.41.1
=> Bump java-test

packages/oxlint/package.yaml
- update to latest oxlint version 0.5.2
- fixes issue https://github.com/mfussenegger/nvim-lint/issues/595 in `nvim-lint`
- the current version of `oxlint` Mason installs doesn't understand the `--format` arg used in the lint config, causing no diagnostics to show inside of nvim
- I have tested the new version as outlined below and can confirm it works, fixing the issue above
=> bump(oxlint): update to 0.5.2

packages/phpactor/package.yaml
In its latest version, phpactor seems to have achieved windows support. We can switch to install their provided PHAR to reduce installation overhead.
=> feat(phpactor): update to v2024.06.30.0 and switch to phar installation

packages/haskell-language-server/package.yaml
Bumps package version for the Haskell Language Server
=> bump(haskell-language-server): Update to version 2.8.0.0

packages/java-debug-adapter/package.yaml
Beep boop. I've updated java-debug-adapter to 0.58.0.
<sup></sup>"#;
=> bump(java-debug-adapter): update to 0.58.0

packages/elp/package.yaml
Supersedes https://github.com/mason-org/mason-registry/pull/6493
Bump `elp`. The new version is built using a newer Erlang/OTP version and therefore the file names changed as well.
https://github.com/mason-org/mason-registry/pull/6493 has test failures. This PR should resolve this.
=> bump(elp): update to v2024-07-16

packages/ocamlformat/package.yaml
Update v0.26.1 to v0.26.2
See [Release Notes](https://github.com/ocaml-ppx/ocamlformat/releases/tag/0.26.2)
=> bump(ocaml-format): v0.26.2

packages/nil/package.yaml
Update `nil` to new [tag](https://github.com/oxalica/nil/releases/tag/2024-08-06), old one does not compile for new `nix` versions
https://github.com/mason-org/mason-registry/issues/6924
Installed and tried on `flake.nix` file
=> bump(nil): update to 2024-08-06

packages/gitui/package.yaml
I've created an issue recently, but I found it's gitui's fault. Their 0.26.2 doesn't work on darwin_x64. #7260
I noticed the upgrading of gitui was failed #5956 , so I upgraded the gitui to 0.26.3 and solved this issue.
#7260 
#5956
=> Upgrade the gitui to 0.26.3

packages/harper-ls/package.yaml
We've added some additional language support and changed our target compiler architecture. This PR fixes the broken filename and highlights this language support.
=> fix(harper-ls): change filename to `-msvc` from `-gnu`

packages/vsg/package.yaml
I added [VSG](https://github.com/jeremiah-c-leary/vhdl-style-guide) which is a VHDL formatter.
Simply installing VSG from mason and using the following lua for [conform.nvim](https://github.com/stevearc/conform.nvim/blob/797d1f622a23d4a21bb58218bdf5999a9beac4ef/lua/conform/formatters/vsg.lua#L8) (which already supports VSG) provides full support:
```lua
require("conform").setup({
formatters_by_ft = {
vhdl = { "vsg" },
},
})
```
=> added VSG (a verilog formatter by jeremiah-c-leary/vhdl-style-guide)

packages/language-server-bitbake/package.yaml
This commit adds a language server for BitBake, which is documented [here](https://github.com/yoctoproject/vscode-bitbake/tree/staging/server) and is also available as an npm package [here](https://www.npmjs.com/package/language-server-bitbake). The language server is already implemented in nvim-lspconfig as [bitbake_ls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#bitbake_ls).
Tested installation via `:Mason`  after pointing at a local registry with:
```lua
require("mason").setup({
registries = {
"file:~/git/mason-registry",
},
})
```
Tested the language server itself with:
```lua
require("lspconfig").bitbake_ls.setup()
```
=> feat: add language-server-bitbake

packages/brunette/package.yaml
Added `brunette` as an alternative to `black` formatted for Python
I have not been able to test the registry as I use nvim nightly and it did not work with either of the options:
```
require("mason").setup({
registries = {
"repo:mason-org/mason-registry",
-- "repo:Zananok/mason-registry",
},
})
```
Same format as `black`. I.e. just install using mason from the list and configure with something like conform:
```
local conform = require("conform")
conform.setup({
formatters_by_ft = {
python = { "brunette" },
},
})
```
=> feat: Add brunette package.yaml file for Python code formatter

packages/protols/package.yaml
Add an LSP for protocol buffer with support for:
- Hover
- Diagnostics
- Go to Definition
- Rename
- Completion
Originally: https://github.com/coder3101/protols
=> feat: add protols LSP for protobuf

packages/java-debug-adapter/package.yaml
Beep boop. I've updated java-debug-adapter to 0.58.1.
=> bump(java-debug-adapter): update to 0.58.1

packages/helm-ls/package.yaml
Bump helm-ls and add the linux_arm64 target, which was added/fixed in https://github.com/mrjosh/helm-ls/pull/124
=> bump(helm-ls): update to 0.2.0 and add linux_arm64

packages/ocaml-lsp/package.yaml
Updated the ocaml-lsp because the old version fails to install for latest Ocaml, v5.3.0
=> bump(ocaml-lsp): update to v1.22.0

packages/ocamlformat/package.yaml
Updated the ocamlformat because the old version fails to install for latest Ocaml, v5.3.0
=> bump(ocamlformat): update to v.0.27.0

packages/tailwindcss-language-server/package.yaml
The release tag for `tailwindcss-language-server` has changed from `@tailwindcss/language-server@vX.X.X` to `vX.X.X` starting from `v0.2.0`, which no longer aligns with the currently specified schema URL.
Ref: https://github.com/tailwindlabs/tailwindcss-intellisense/tags
Therefore, I have updated the schema URL to match the current release tag and update `tailwindcss-language-server` version to `v0.14.1`
=> Update Schema URL for TailwindCSS Language Server

packages/elp/package.yaml
Upstream provides Linux arm64 builds, this adds them to the `package.yaml`.
=> Add ARM64 build of elp

packages/superhtml/package.yaml
Added the superhtml lsp to the list of packages that mason can install.
Example using mason-lspconfig (PR coming soon)
LSP Showint up in :LspInfo
Installed through Mason
Not quite ready for prime time since the LSP itself doesn't fully work yet (that or I've set it up wrong) https://github.com/kristoff-it/superhtml/issues/20.
=> feat: add superhtml package

packages/shopify-theme-check/package.yaml
Add deprecated message for theme-check since the repo is archived, moved to [Shopify/theme-tools](https://github.com/Shopify/theme-tools).
see https://github.com/Shopify/theme-check
It took me sometime to figure out `shopify-cli` has wrapped the new theme check lsp. Hope this can help some people.
=> chore: add deprecated message for theme-check

packages/bash-language-server/package.yaml
Add other shells to bash-language-server languages because it would work for other shell configuration files as well.
=> tweak: add other shells bash-language-server supports

packages/pymarkdownlnt/package.yaml
Added the pymarkdownlnt linter from pypi
Demo of pymarkdownlnt in mason, and custom linter with with nvim-lint:
https://asciinema.org/a/18LTFNOd6x3ptQZFp3Slx4rbd
nvim-lint config (lazy):
```lua
{
"mfussenegger/nvim-lint",
opts = {
linters_by_ft = {
markdown = { "pymarkdownlnt" },
},
linters = {
pymarkdownlnt = {
cmd = "pymarkdownlnt",
stdin = true,
args = { "scan-stdin" },
stream = nil,
ignore_exitcode = true,
parser = require("lint.parser").from_errorformat("stdin:%l:%c: %m", {
source = "pymarkdownlnt",
severity = vim.diagnostic.severity.WARN,
}),
},
},
},
}
```
=> feat: add pymarkdownlnt

packages/duster/package.yaml
[Duster](https://github.com/tighten/duster) combines different PHP formatters and linters and runs them all simultaneously. It should work similarly to [Pint](https://github.com/mason-org/mason-registry/blob/main/packages/pint/package.yaml), [PHPCS](https://github.com/mason-org/mason-registry/blob/main/packages/phpcs/package.yaml), or [PHP-CS-Fixer](https://github.com/mason-org/mason-registry/blob/main/packages/php-cs-fixer/package.yaml) (since it wraps those packages).
=> Feat: Adds Duster as a PHP Formatter/Linter Option

packages/fennel-ls/package.yaml
This should close #5265
Updates `fennel-ls` and lets it run on CI again.
#5265: https://github.com/mason-org/mason-registry/issues/5265
=> chore(fennel-ls): Update package and remove CI skipping

packages/prettydiff/package.yaml
This change adds a simple package definition to allow the installation of `prettydiff` via Mason.
Prior to this change, there was no support for the `prettydiff` formatter when using Mason with neovim.
=> Add support for the `prettydiff` formatter

packages/angular-language-server/package.yaml
angularls has the wrong typescript dependency for v19 and there is no option for v18.
=> Add angularls v18 and fix typescript dependency for v19.

packages/systemd-language-server/package.yaml
This adds the systemd-language-server package.
~~I didn't know how to test this, I just copied and adjusted from another pypi package 😅~~
Tested and works 👍
=> feat: add systemd-language-server

packages/nextflow-language-server/package.yaml
- **feat: add nextflow-language-server**
- **fix(nextflow): Try going in a different direction**
- **chore(nextflow): Clean up version**
- **fix(nextflow): use vsix instead of zip**
- **chore(nextflow): Update to original repo**
Adds the Nextflow language server that's in the VS Code extension.
Let me know if there's a better way of doing this!
=> Add Nextflow language server

packages/kube-linter/package.yaml
KubeLinter analyzes Kubernetes YAML files and Helm charts and checks them against various best practices, with a focus on production readiness and security.
This PR adds the kube-linter package to the mason registry.
=> Add kube-linter

packages/dotenv-linter/package.yaml
Adds dotenv linter for .env files
=> feat: add dotenv-linter

packages/air/package.yaml
Adds the [Air](https://github.com/posit-dev/air) formatter/LSP for R.
NB, Air was [recently added](https://github.com/neovim/nvim-lspconfig/pull/3614) to nvim-lspconfig.
I've tested installation for all platforms, and confirmed that the installation works and can be set up and configured using nvim-lspconfig (using the branch from the linked pull request).
This doesn't yet work with mason-lspconfig; I'll open a separate PR there. 
For some reason I found that I needed to use `bin: air-aarch64-apple-darwin/air` rather than `bin: air`, which is the format which other packages seem to use. I wasn't able to get to the bottom of why this was necessary - grateful if anyone could shed some light on this.
Thank you!
=> feat: add air language server

packages/pyproject-fmt/package.yaml
This adds the [`pyproject-fmt`](https://pypi.org/project/pyproject-fmt/) formatter as a package. I marked it down as both TOML and Python language since it does directly pertain to Python projects and should show up if people search for Python, but it also formats a specific type of TOML file so I marked that as well.
=> feat: add pyproject-fmt

packages/oxlint/package.yaml
This merge request updates the `oxlint` package to use npm. (Sorry for not waiting for a response in the related issue, I had too much free time on my hands :joy:) It also adds the `oxlint_language_server` binary.
Closes #8709
=> feat(oxlint): add language server, bump to 0.15.8

packages/codelldb/package.yaml
The `lldb` folder with the binaries and the library files are important files for setting up the debugger and should be marked as stable files. This is part of the efforts for the migration to Mason v2
=> feat(codelldb): expose the `lldb` library as a shared folder

packages/language-server-bitbake/package.yaml, packages/oelint-adv/package.yaml
The casing of `BitBake` is incorrect and should be resolved.
=> fix: fix capitalization of `BitBake` filetype

packages/codelldb/package.yaml
The path to the `lldb` library is incorrect. This resolves it
=> fix(codelldb): fix incorrect `lldb` path

CONTRIBUTING.md
Remove unneeded recommendation to use `SchemaStore.nvim`. 
`yaml-ls` alone is already able to display diagnostics & autocompletion for yaml files, if the schema is registered at the schema store (which is the case for mason registry yaml schema).
=> docs: remove unneeded recommendation to use `SchemaStore.nvim`

packages/api-linter/package.yaml
fix: typo in api-linter definition
#9653
=> fix: typo in api-linter definition

packages/cairo-language-server/package.yaml
Removes the vscode lsp schema as the vscode folder doesn't exist anymore. Blocks a lot of CIs
=> feat(cairo): remove lsp schema (repo doesn't exist)

packages/ruff-lsp/package.yaml
Added deprecation message to `ruff-lsp` package.yaml.
Followed example from [xo](https://github.com/mason-org/mason-registry/blob/main/packages/xo/package.yaml), but noticed at the same time [CONTRIBUTING.md](https://github.com/mason-org/mason-registry/blob/main/CONTRIBUTING.md#package-specification) package specs doesn't include the `deprecation` keyword.
- https://github.com/mason-org/mason-registry/issues/9707
- https://github.com/astral-sh/ruff-lsp/pull/520
Removed because not applicable.
=> chore(ruff-lsp): add deprecation message

packages/just-lsp/package.yaml
This PR simply adds linux arm and gnu targets for the `just-lsp` lsp server. Pretty much whatever was missing from the [supported packages](https://github.com/terror/just-lsp/releases/tag/0.2.1).
=> feat(just-lsp): add additional targets

packages/dotenv-linter/package.yaml, packages/nginx-config-formatter/package.yaml, packages/ntt/package.yaml, packages/tilt/package.yaml, packages/typstfmt/package.yaml, packages/vhdl-style-guide/package.yaml
(I created a new branch to make things clearer.)
=> fix(typstfmt): add deprecation notice

packages/haskell-language-server/package.yaml
Update Haskell Language Server to version 2.10.0.0 and the supported binary versions specified [here](https://github.com/haskell/haskell-language-server/releases/tag/2.10.0.0)
=> bump(haskell-language-server): Update to version 2.10.0.0

.github/workflows/package-tests.yaml
Allows skipping the entire package tests job if this label is present. Useful/needed for sweeping registry changes such as #9774.
=> ci: skip package tests if PR has `ci:skip-package-tests` label

packages/emmylua_ls/package.yaml, packages/just-lsp/package.yaml, packages/ltex-ls-plus/package.yaml, packages/ts_query_ls/package.yaml
follow-up to #9774, add missing `neovim.lspconfig` to some LSPs.
=> feat: add missing nvim-lspconfig specs to some LSPs

packages/protols/package.yaml
Set `neovim.lspconfig` mapping for `protols`
`protols` is a valid server in nvim-lspconfig (see https://github.com/neovim/nvim-lspconfig/blob/master/lsp/protols.lua) and it should have the `neovim.lspconfig` property set.
I mentioned this in https://github.com/mason-org/mason-registry/pull/9774#issuecomment-2857982842
Installing protols automatically
protols successfully installed
Diagnostics
=> feat(protols): specify neovim.lspconfig mapping

packages/omnisharp/package.yaml
With the new way how Language Server Config can be provided in neovim, we changed the default binary to match the ones provided inside the package:
See official repo docs how binaries are named in the official package (`OmniSharp` and`OmniSharp.exe`):
https://github.com/OmniSharp/omnisharp-roslyn?tab=readme-ov-file#building
See new LSP config for OmniSharp:
https://github.com/neovim/nvim-lspconfig/blob/master/lsp/omnisharp.lua#L19
The benefit in doing so, would be that the LSP config does not have to change if the binary is in users PATH, and could be picked up, resulting in hopefully 'just work experience', regardless if the user installed the server manually or with Mason. 
For MacOS I expect it to work as it works for Linux.
=> feat: use OmniSharp/OmniSharp.exe binary provided in the package

packages/terraform/package.yaml
Added terraform, a Hashicorp tool that comes with built-in `fmt` commands for files of their type. 
Split from: https://github.com/mason-org/mason-registry/pull/8383
=> feat: Add terraform

packages/pyrefly/package.yaml
I'm part of the Pyrefly team at Meta, and we're working on a new language server/type checker (called Pyrefly 😄, [website](https://pyrefly.org/), [github](https://github.com/facebook/pyrefly)) to replace our other Python language server, Pyre. Pyre isn't fully ready to be deprecated yet, but we just made our big announcement at PyCon this year, and are excited for users to test it out.
I'd love to add it to Mason when possible, since it would make it super easy to install/use!
This PR adds the `packages/pyrefly/package.yaml` file, which enables Pyrefly in the Mason UI and enables users to install.
- [>1k stars](https://github.com/facebook/pyrefly)
- Relevant user bases: [VSCode](https://marketplace.visualstudio.com/items?itemName=meta.pyrefly), …
=> feat: add Pyrefly

packages/tofu-ls/package.yaml
Add [OpenTofu language server](https://github.com/opentofu/tofu-ls).
[OpenTofu](https://opentofu.org/) is a [FOSS fork of Terraform](https://opentofu.org/blog/the-opentofu-fork-is-now-available/).
- none
- tofu-ls is pretty new, but since OpenTofu is a fork of Terraform, I'm assuming it will get adopted pretty fast
- [nvim-lspconfig MR](https://github.com/neovim/nvim-lspconfig/pull/3874) (Merged)
- Related [nvim-lint MR](https://github.com/mfussenegger/nvim-lint/pull/801)
=> feat: add tofu-ls

packages/alejandra/package.yaml
Precompiled binaries only target Linux (x86_64 & arm64 musl) and don’t support other platforms like aarch64-darwin. Using the cargo source ensures cross-platform compatibility.
Switched the `source` in alejandra/package.yaml from a precompiled binary to building from source using cargo (pkg:cargo/alejandra_cli@4.0.0). This change allows installation and usage on non-Linux platforms such as aarch64 (macOS)
=> fix(alejandra): switch to cargo source instead of precompiled binaries

packages/taplo/package.yaml
`Taplo` is also a formatter, see [this link](https://taplo.tamasfe.dev/configuration/formatter-options.html).
Setting Taplo to be a Conform formatter worked in my set up. Also updating it in Mason registry.
=> feat(taplo): add formatter category

packages/ols/package.yaml
Added a package for an arm64 linux build of odin language server https://github.com/DanielGavin/ols
Builds of ols for other architectures are already available through Mason.
The arm build was not previously provided by upstream simply because nobody yet contributed the build script to their CI.
(resolved in https://github.com/DanielGavin/ols/pull/674)
=> add linux arm64 package for ols (odin language server)

packages/qmlls/package.yaml
> The qmlls is now provided as prebuilt binary.
> Nightly versions currently follow an incompatible version scheme and will be fixed upstream.
What is the recommended strategy to update it here in the future? :)
=> feat: add qmlls

packages/qmlls/package.yaml
Added lspconfig mapping for qmlls to have it be automatically enabled with mason-lspconfig
=> added 'neovim.lspconfig' mapping for qmlls

packages/nomad/package.yaml
Added nomad, a Hashicorp tool that comes with built-in `fmt` commands for files of their type. 
Split from: https://github.com/mason-org/mason-registry/pull/8383
=> feat: Add nomad

packages/prometheus-pint/package.yaml
Adding the prometheus rule linter known as 'pint'. The mason package name is 'prometheus_pint' since there is already a different pint package (a php code formatter).
The tool has close to 1000 stars on Github and is maintained by Cloudflare.
It is *not* yet supported by `nvim-lint` but will be soon.
I am able to test with Linux on amd64. All other architectures are best guess.
=> feat(pint) - prometheus rule linter

packages/vscode-java-dependency/package.yaml
This pull request introduces the `vscode-java-dependency` package to the registry. This package is a crucial dependency for a new Neovim plugin I am developing called [java-deps.nvim](https://github.com/g0ne150/java-deps.nvim).
The `java-deps.nvim` plugin aims to provide functionality similar to the popular VS Code extension [vscode-java-dependency](https://open-vsx.org/extension/vscjava/vscode-java-dependency), allowing users to view Java projects and dependencies. The main functionality of this plugin has already been developed and tested.
For `java-deps.nvim` to work correctly, it requires the language server and associated utilities provided by `vscode-java-dependency`. Adding this package to `mason-registry` will allow users to easily and automatically install this dependency, …
=> feat(add): package vscode-java-dependency

packages/wgsl-analyzer/package.yaml
A `versioning:loose` renovate directive has been added to the `wgsl-analyzer` package.yaml. This is done because the release versioning scheme has been changed from semantic versioning to a date based system since the original introduction of the `wgsl-analyzer` package (see https://github.com/wgsl-analyzer/wgsl-analyzer/releases). The same `versioning=loose` directive has been found in other packages with date based release schemes (e.g. rust-analyzer), so this seemed like the most straightforward solution.
I have not tested this in Neovim, but this does not change the `wgsl-analyzer` package in any meaningful way. It does, however, enable the renovate bot to update the `wgsl-analyzer` package when new releases are available, so I have tested this locally with renovate. The output of …
=> fix(wgsl-analyzer): Make Renovate update wgsl-analyzer releases

packages/wgsl-analyzer/package.yaml
Bumps the `wgsl-analyzer` version the same way that renovatebot does in https://github.com/mason-org/mason-registry/pull/10977, but also updates the `assets` mappings to the types in the newest releases.
The `bin` mapping is also changed from `wgsl_analyzer` to `wgsl-analyzer` to reflect the config for `wgsl-analyzer` in lspconfig (see https://github.com/neovim/nvim-lspconfig/blob/master/lsp/wgsl_analyzer.lua). This may cause a breaking change in some lsp configs using mason, but should also enable `wgsl-analyzer` to work without any changes to the lsp config `cmd` value on a new config.
#10028
=> bump(wgsl-analyzer): update to v2025

packages/emmylua-codeformat/package.yaml
I would like to add the EmmyLuaCodeStyle formatter, which is also included in lua_ls.
https://github.com/CppCXY/EmmyLuaCodeStyle
=> feat: add emmylua-codeformat

packages/omnisharp/package.yaml
reverted back partially the changes made by me in https://github.com/mason-org/mason-registry/pull/9738 as they cause issues on macos arm64 arch.
It seems to be a better approach to use the `.dll`.
The change that stays is the renaming from `omnisharp` to `OmniSharp`.
fixes: https://github.com/mason-org/mason-registry/issues/10084
PS: sorry for the trouble :(
=> revert(omnisharp): partially revert config to fix #10084

packages/haskell-language-server/package.yaml
> [!NOTE]
> Blocked until `ghcup` is updated to include the latest version of HLS
Update Haskell Language Server to version 2.11.0.0 and the supported binary versions specified [here](https://github.com/haskell/haskell-language-server/releases/tag/2.11.0.0)
=> bump(haskell-language-server): Update to version 2.11.0.0

packages/angular-language-server/package.yaml
Add missing angular-language-server v19 stanza and fix typescript dep for v20
=> Add missing angular-language-server v19 stanza and fix typescript dep for v20

packages/kdlfmt/package.yaml
Added a new package definition for `kdlfmt`, a Rust-based code formatter for KDL documents. The package uses the latest release from crates.io and exposes the `kdlfmt` binary via Mason. This enables users to easily install and use `kdlfmt` for formatting `.kdl` files through Mason.
- [kdlfmt on crates.io](https://crates.io/crates/kdlfmt)
- [kdlfmt GitHub repository](https://github.com/hougesen/kdlfmt)
- [Formatter requirements in CONTRIBUTING.md](https://github.com/mason-org/mason-registry/blob/main/CONTRIBUTING.md#requirements)
- Successfully tested installation and formatting of `.kdl` files locally.
(Not applicable)
=> feat: add kdlfmt package (KDL formatter, Rust/cargo-based)

packages/docker-language-server/package.yaml
Added docker-language-server
#11059
- at the moment 81 https://github.com/docker/docker-language-server
- Not sure here. Package is published by docker org
- Already merged into master https://github.com/neovim/nvim-lspconfig/commit/e3d837b
- Package is published by docker org on 16 july because of that usage is inevitable 
Successfully started server inside nvim and got diagnostics for Dockerfile from server
=> feat(docker-language-server): add lsp server

packages/docker-language-server/package.yaml
Mistake in previous PR – incorrect lspconfig name
https://github.com/neovim/nvim-lspconfig/commit/e3d837b#diff-0e52ccaf020d4b83905c5231e4a62e95a1d06298b97e13bd97ef241c6f155fff
=> fix(docker-language-server): lspconfig server name

packages/elp/package.yaml
This PR updates the Erlang Language Platform version used by Mason.
The archive for version 27.1 is no longer available under the tag 2025-07-21, which is the tag Mason uses to install the server. To ensure installation works correctly, I bumped the version to 27.3, which is available under the same tag.
https://github.com/WhatsApp/erlang-language-platform/releases/tag/2025-07-21
Failed to download file "https://github.com/whatsapp/erlang-language-platform/releases/download/2025-07-21/elp-linux-x86_64-unknown-linux-gnu-otp-27.1.tar.gz".
=> bump elp version 27.1 to 27.3

CONTRIBUTING.md
In various PRs, we had discussions what "a relevant number of users" means in regard to VS Code Marketplace downloads. Specifying a concrete number should be helpful to make things clearer to people considering adding a new package.
I chose the number 5000, because of VS Code's large user base, and because downloads are done passively, as opposed to the active act of starring a repo on GitHub. It's more of a ballpark, so a tool with 4995 downloads would still be fine of course, but ~300 downloads are imho not sufficient to count as a relevant user base.
=> docs: more explicit requirements

packages/ocaml-lsp/package.yaml
update ocaml-lsp to v1.23.0 because v1.22.0 has some issues like https://github.com/ocaml/ocaml-lsp/issues/1531
https://github.com/ocaml/ocaml-lsp/releases/tag/1.23.0
=> bump(ocaml-lsp): update to v1.23.0

packages/codebook/package.yaml
Added codebook that has been recently added to neovim's lspconfig repo.
https://github.com/neovim/nvim-lspconfig/blob/master/lsp/codebook.lua
=> feat: add codebook

packages/copilot-language-server/package.yaml
Add lspconfig's name of `copilot-language-server`: `copilot`
Refer to https://github.com/neovim/nvim-lspconfig/blob/master/lsp/copilot.lua
=> feat(copilot): add nvim's lspconfig name

packages/goimports-reviser/package.yaml
`goimports-reviser` started releasing linux-arm64 binary from v3.9.1 onwards:
https://github.com/incu6us/goimports-reviser/releases/tag/v3.9.1
Let's update the registry entry to include the same.
Add linux-arm64 binary for `goimports-reviser`
1. `goimports-reviser` listed in the `Installed` list
2. `uname -a` output captured in the bottom panel via `:lua vim.system({"uname", "-a"})`
=> feat(goimports-reviser): Add linux-arm64 binary.

packages/rpm-spec-language-server/package.yaml, packages/rpm_lsp_server/package.yaml
New package with LSP for RPMs spec-files.
The LSP is present at `nvim-lspconfig`: https://github.com/neovim/nvim-lspconfig/blob/master/lsp/rpmspec.lua
Successful start of LSP in Neovim.
=> Add package rpm-spec-language-server

packages/zuban/package.yaml
Introduce Zuban - a high performant LSP and type checker for Python built in Rust by [David Halter](https://github.com/davidhalter).
#11731
1. Approved at [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#zuban).
2. Has [377 stars](https://github.com/zubanls/zuban/stargazers) on Github.
=> feat: add zuban lsp
